### PR TITLE
Proposes to rename buildpacks

### PR DESCRIPTION
**Pull request by dmikusa-pivotal**
## Summary

A proposal to use a new naming convention & rename existing buildpacks.

[Readable Link](https://github.com/paketo-buildpacks/rfcs/blob/buildpack-rename/text/0000-buildpack-rename.md)

### CODE REVIEW

**Review by ekcasey — APPROVED** [review]
Seems reasonable enough

**Comment by fg-j** [comment]
From Working Group 7/19/22:

- Today, it's hard to maintain consistency in how we refer to buildpacks in the documentation. There's no style guide that says "write 'Paketo Buildpack for .NET Core' not 'the Paketo Dotnet buildpack'. 
- We could use tooling and/or a style guide to enforce the way we refer to buildpacks

**Comment by joshuatcasey** [comment]
2022-07-26 Working Group notes: waiting for feedback/approvals

**Review by ryanmoran — APPROVED** [review]

**Review by fg-j — APPROVED** [review]

**Comment by dmikusa-pivotal** [comment]
2022-08-02 WG Notes:

Ready to merge.

**Pull request merged**
