### PR TITLE
Add an RFC for removing shell specific interfaces

### PR DESCRIPTION
**Pull request by samj1912**
## Summary

Remove shell specific interfaces.
[Readable](https://github.com/samj1912/rfcs-1/blob/direct/text/0000-direct.md)

## Use Cases

See RFC.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by dmikusa-pivotal** [comment]
+1 for the idea.

In regards to the RFC, I would like to see an implementation section. I think my idea would be to perhaps have a bullet list that includes the actions we need to take here. 

1. Create an issue to review & catalog our present compliance.
2. Open issues for non-compliant buildpacks to investigate making the change.
3. Open issues to switch where possible.

It might also be interesting to talk about a process for cases where we need to change APIs. On one hand, we can't just make changes and break users, but on the other, we need a plan to migrate buildpacks to use this new method. Or perhaps we could defer this decision to each individual buildpack that needs changes to be compliant.

**Comment by fg-j** [comment]
Do we have any idea when this is expected to land in the lifecycle?

**Comment by ekcasey** [comment]
@fg-j 

> Do we have any idea when this is expected to land in the lifecycle? Here's the issue to implement the change. I don't see it added to any milestone.

The short answer is that it is currently unscheduled. Since this RFC removes support for `<app>/.profile` scripts from the launcher, some core team members are uncomfortable implementing this change before we approve a version of System Buildpacks which would allow platforms to provide support for `<app>/.profile` script via a buildpack.

**Review by ekcasey — APPROVED** [review]

**Comment by dmikusa-pivotal** [comment]
@ekcasey 

> > It might also be interesting to talk about a process for cases where we need to change APIs. On one hand, we can't just make changes and break users
> 
> Are there any cases where we would need to change user facing APIs? I believe we should be able to move to direct processes without affecting end users.

The only thing coming to mind at the moment is `.profile`. It is not something that I think we widely advertise, but it is supported and user-facing. That won't continue to work. Ideally, we'll have a workaround so users hopefully won't have to care.

I think my comment more was to make sure that we are considering the possible implications this might cause. Java buildpacks have been using direct for a while so are unlikely to be impacted, but each language family will probably need to evaluate the question of what might break, if anything.

**Review by ryanmoran — APPROVED** [review]

**Review by dmikusa-pivotal — APPROVED** [review]

**Comment by dmikusa-pivotal** [comment]
We discussed this in the WG meeting today. In principle, everyone is in agreement that this is a good proposal. We've got enough approvals and this will get merged.

In practice, there are some concerns for specific language families where the impact of losing shell scripting and `.profile` script access might cause problems for users. We discussed leaving the implementation of this up to the individual language family. Allowing them to determine the impact and set a timeline to implement this RFC. If that means waiting until there is a profile buildpack, or some other similar means of solving that problem, that is OK and can be determined at the language team's discretion. 

After merging, I'll create an issue where we can track at the language family level where this has been implemented.

**Pull request merged**
